# Generated by Django 4.2.13 on 2024-05-27 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be in the format: 8-xxx-xxx-xxxx', regex='^8-\\d{3}-\\d{3}-\\d{4}$')])),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
