# Generated by Django 4.2.13 on 2024-05-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aromat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Объем')),
            ],
            options={
                'verbose_name': 'Аромат',
                'verbose_name_plural': 'Ароматы',
            },
        ),
    ]
