# Generated by Django 4.2.13 on 2024-06-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_seller_alter_administrator_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aromat',
            name='price',
        ),
    ]
