# Generated by Django 4.2.13 on 2024-06-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_remove_aromat_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldAromat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название аромата')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Объем')),
                ('masla', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Масла')),
                ('paymenttype', models.CharField(max_length=50, verbose_name='Тип оплаты')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Касса')),
                ('date', models.DateField(verbose_name='Дата')),
                ('sellername', models.CharField(max_length=100, verbose_name='Имя продавца')),
            ],
            options={
                'verbose_name': 'Проданные ароматы',
                'verbose_name_plural': 'Проданные ароматы',
            },
        ),
    ]
