# Generated by Django 4.2.13 on 2024-06-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_soldaromat_masla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldaromat',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='soldaromat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Касса'),
        ),
    ]
