# Generated by Django 4.2.13 on 2024-06-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_soldaromat_date_alter_soldaromat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldaromat',
            name='seller_id',
            field=models.IntegerField(default=1, verbose_name='ID продавца'),
            preserve_default=False,
        ),
    ]
