# Generated by Django 4.2.13 on 2024-06-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_soldaromat_seller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldaromat',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='soldaromat',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.seller'),
        ),
    ]
