# Generated by Django 4.2.13 on 2024-06-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_branch_alter_administrator_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
    ]
