# Generated by Django 4.2.13 on 2024-06-06 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_alter_branch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aromat',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.branch', verbose_name='Филиал'),
            preserve_default=False,
        ),
    ]
