# Generated by Django 4.2.13 on 2024-06-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_soldaromat_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(max_length=25, verbose_name='Пароль'),
        ),
    ]
