# Generated by Django 4.2.13 on 2024-06-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_alter_seller_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aromat',
            name='code',
            field=models.CharField(max_length=3, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='aromat',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
