# Generated by Django 4.2.13 on 2024-06-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_alter_aromat_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldaromat',
            name='code',
            field=models.CharField(max_length=5, verbose_name='Код'),
        ),
    ]
