# Generated by Django 4.2.13 on 2024-06-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_alter_soldaromat_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldaromat',
            name='coment',
            field=models.CharField(max_length=5000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Пароль'),
        ),
    ]
